# Generated by Django 3.0.3 on 2020-02-27 06:30

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200227_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='create time')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile')),
                ('active', models.IntegerField(max_length=1, verbose_name='active')),
                ('sex', models.CharField(max_length=2, verbose_name='sex')),
                ('recommender', models.IntegerField(verbose_name='recommender')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='polls.Question', verbose_name='parent question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published date'),
        ),
    ]
