# Generated by Django 3.0.3 on 2020-02-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200227_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='update time')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='create time')),
                ('name', models.CharField(max_length=20, verbose_name='member type name')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
    ]
