# Generated by Django 3.0.3 on 2020-02-27 23:43

from django.db import migrations
from polls.models import Member


def combine_names2(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    member_list = apps.get_model('polls', 'Member')
    for member in Member.objects.all():
        member.name = '%s %s' % (member.last_name, member.first_name)
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_member_name2'),
    ]

    operations = [
        migrations.RunPython(combine_names2),
    ]
