# Generated by Django 3.0.3 on 2020-02-27 23:48

from django.db import migrations
from polls.models import MemberType


def initalize_member_type(apps, schema_editor):
    member_list = apps.get_model('polls', 'Member')
    if len(member_list) > 0:
        return True
    MemberType(name=_('member level 1')).save()
    MemberType(name=_('member level 2')).save()
    MemberType(name=_('member level 3')).save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200228_0743'),
    ]

    operations = [
    ]
