# Generated by Django 3.0.3 on 2020-02-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200228_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='color_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
